title: Surajit Saikia # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student in AI with interest in Deep Reinforcement learning, robotics and self-driving cars
  <br><br>
   Universidad de Leon, Spain.       
   University of Groningen, Netherlands.         
   Sri Sathya Sai Institute of Higher Learning, India        
  <br><br>
  <a href="https://www.linkedin.com/in/surajit-saikia-55b717101/">My LinkedIn Profile</a> 
  <br><br>
  <a href="https://surjeetsaikia.medium.com/">Medium</a> 
  <br><br>
  <a>Contact me at: ssai@unileon.es</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
